/*
	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not 
	exceed four million, find the sum of the even-valued terms.
	
	March 27,2012
*/

public class Problem2{
	public static void main(String [] args){
		int limit=40,total=0;
		int [] seq=new int [limit];
		seq[0]=0;
		seq[1]=1;
		for(int i=2;i<limit;i++){
			seq[i]=seq[i-1]+seq[i-2];
			if(seq[i]%2==0){
				total+=seq[i];
			}else if(seq[i]>4000000){
				break;
			}
		}
		for(int i=0;i<limit;i++){
			System.out.print(seq[i]+" ");
		}
		System.out.println("\n"+total);
	}
}
